---
# tasks file for zookeeper
#
# Disable firewalld, Sellinux, update all packages, install java
 - name: Server preparation
   import_tasks: preparation.yml
   tags:
     - preparation


# Installation of zookeeper
 - name: Server installation
   import_tasks: installation.yml
   tags:
     - installation
     - zoo

# Configure  
 - name: Server configuration
   import_tasks: configuration.yml
   tags:
     - configuration
     - zoo
